### ISSUE TITLE
Invalid Version: 3.0.0rc1

### ISSUE THREAD

**Issue by makc** [mkuklis/phonegap-websocket#7]
```
localhost:test makc$ phonegap local plugin add https://github.com/mkuklis/phonegap-websocket
[phonegap] adding the plugin: https://github.com/mkuklis/phonegap-websocket

/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:257
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 3.0.0rc1
    at new SemVer (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:257:11)
    at compare (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:410:10)
    at eq (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:449:10)
    at cmp (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:473:41)
    at Comparator.test (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:546:10)
    at testSet (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:818:17)
    at Range.test (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:810:9)
    at Function.satisfies (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/node_modules/semver/semver.js:831:16)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/src/install.js:112:59
    at Array.forEach (native)
```

```
localhost:test makc$ cordova plugin add https://github.com/mkuklis/phonegap-websocket
cp: dest file already exists: /Users/makc/test/plugins/org.apache.cordova.plugin.websocket.WebSocket/README.md

skipping existing file: java_websocket.jar
cp: dest file already exists: /Users/makc/test/plugins/org.apache.cordova.plugin.websocket.WebSocket/README.md
cp: dest file already exists: /Users/makc/test/plugins/org.apache.cordova.plugin.websocket.WebSocket/plugin.xml

skipping existing file: CordovaClient.java
skipping existing file: WebSocket.java
skipping existing file: phonegap-websocket.js
[Error: Plugin doesn't support this project's Cordova version. Project version: 3.0.0-rc1, failed version requirement: 3.0.0]
localhost:test makc$ 

```

**Comment by shadimsaleh** [comment]
hi  I sill have an error , the demo not work :(
anther question how i can send photo or video 
thank

**Comment by makc** [comment]
just drop the photo in comment box:

![frog](https://cloud.githubusercontent.com/assets/242577/10254775/16447db4-6946-11e5-861a-5c30c1074e24.gif)
